'''#x=2345
print("enter the number")
x=int(input())
y=x/10
#z=y%10
print(y)'''
"""print("enter two number")
x=int(input("enter first number"))
y=int(input("enter second number"))
print("before swapping")
x=x+y
y=x-y
x=x-y
print("after swapping",x,y)"""
'''print("enter the number")
x=int(input("enter the number"))
y=int(input("enter the number"))
z=x**y
print("the power of x",z)'''
print("enter the number")
x=int(input("Enter the number"))
y=x%10
x=y
print(x)
